name: Publish to PyPI

on:
  pull_request:
  push:
    branches:
      - main
  release:
    types:
      - published

defaults:
  run:
    shell: bash

jobs:
  packages:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Get tags
      run: git fetch origin 'refs/tags/*:refs/tags/*'

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"

    - name: Install build tools
      run: |
        python -m pip install --upgrade pip build twine

    - name: Build binary wheel
      run: python -m build --sdist --wheel . --outdir dist

    - name: CheckFiles
      run: |
        ls -lh dist

    - name: Test wheels
      run: |
        cd dist && python -m pip install compliance_checker*.whl
        python -m twine check *

    - name: Publish a Python distribution to PyPI
      if: success() && github.event_name == 'release'
      uses: pypa/gh-action-pypi-publish@v1.5.0
      with:
        user: __token__
        password: ${{ secrets.PYPI_ACCESS_TOKEN }}
